logging:
  level: INFO
  format: json
  output: stdout
  file_path: /var/log/mctrader/app.log

data:
  root_path: ./data
  orderbook_diff_path: orderbook_diff
  trade_path: trade

exchange:
  default: bithumb
