#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
scripts/lib/gen_deferred_followup_baseline.py
CFP-2591 Phase 2 / ADR-060 §결정 6 — deferred-followup baseline single writer (generate/prune)

승격 시점(Clean-as-You-Code) registry FLAG 집합 + 비-registry declaration surface 를 동결한
`docs/deferred-followup-baseline.yaml` 을 **생성/전정**하는 단일 writer. baseline 은 수기 편집 금지
— 반드시 본 tool 로 생성 (gate/lint 가 grandfather 판정에 사용, content_digest tamper-evident).

determinism (ID-1): 동일 HEAD → byte-identical 파일. generated_at 은 wall-clock 금지 —
git commit date (%cI) 유도 (clock 비의존). entry 정렬 결정적 (gate_flags: name / surfaces: locator).

Usage:
  python3 gen_deferred_followup_baseline.py generate [--repo-root <p>] [--registry <p>] [--out <p>]
  python3 gen_deferred_followup_baseline.py prune    [--repo-root <p>] [--baseline <p>]

  generate — registry FLAG (gate.classify_entry tier==FLAG) + carrier.scan_repo() 전건 동결.
  prune    — baseline 재평가, 해소분 drop (monotonic shrink only), digest 재계산 후 write.

ADR refs: ADR-060 §결정 6 / ADR-061 / ADR-005 / ADR-127
"""

import argparse
import os
import subprocess
import sys

import yaml

# scripts/lib 를 sys.path 에 추가 후 sibling 모듈 import (동일 디렉토리 재사용 — 신규 lib 추출 금지).
_LIB_DIR = os.path.dirname(os.path.abspath(__file__))
if _LIB_DIR not in sys.path:
    sys.path.insert(0, _LIB_DIR)

import check_deferred_followup_reconcile as gate  # noqa: E402
import check_deferral_carrier_declared as carrier  # noqa: E402

# Windows cp949 인코딩 문제 회피: stdout/stderr 를 UTF-8 강제 (ADR-061 portability)
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")


SCHEMA_VERSION = "1.0"
GENERATED_BY = "CFP-2591"
BASIS_TEXT = (
    "ADR-060 §결정6 승격 시점 registry+declaration FLAG 집합 동결 "
    "(Clean-as-You-Code new-only, CFP-2591)"
)
SURFACE_REASON = "pre-existing (CFP-2591 baseline snapshot grandfather)"

# 생성 파일 header (상수 — 결정성 무해, human 안내).
_HEADER = (
    "# docs/deferred-followup-baseline.yaml — GENERATED by "
    "scripts/lib/gen_deferred_followup_baseline.py (CFP-2591)\n"
    "# DO NOT EDIT BY HAND. Regenerate: bash scripts/gen-deferred-followup-baseline.sh generate\n"
    "# content_digest = sha256 over canonical {gate_flags, declaration_surfaces} "
    "(provenance/generated_at 제외).\n"
)


# ─────────────────────── provenance (clock 비의존) ────────────────────────────────

def _git_head_sha(repo_root):
    out = subprocess.run(
        ["git", "-C", repo_root, "rev-parse", "HEAD"],
        capture_output=True, text=True, check=True, encoding="utf-8", errors="replace",
    ).stdout.strip()
    return out


def _git_head_committer_date(repo_root):
    out = subprocess.run(
        ["git", "-C", repo_root, "show", "-s", "--format=%cI", "HEAD"],
        capture_output=True, text=True, check=True, encoding="utf-8", errors="replace",
    ).stdout.strip()
    return out


# ─────────────────────── collectors (재사용 SSOT) ────────────────────────────────

def collect_gate_flags(entries, repo_root):
    """
    registry entries[] → tier==FLAG 만 {name, frozen_count, frozen_threshold, absent_axes}.
    name 오름차순 정렬 (결정성).
    """
    out = []
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        result = gate.classify_entry(entry, repo_root)
        if result is not None and result["tier"] == "FLAG":
            out.append({
                "name": result["name"],
                "frozen_count": int(result["count"]),
                "frozen_threshold": int(result["threshold"]),
                "absent_axes": list(result["absent_axes"]),
            })
    out.sort(key=lambda g: g["name"])
    return out


def collect_declaration_surfaces(repo_root):
    """
    carrier.scan_repo() 전건 → {locator, token, reason}. locator 오름차순 정렬 (결정성).
    """
    findings = carrier.scan_repo(repo_root)
    out = []
    for rel, line, token, _ctx in findings:
        out.append({
            "locator": "%s:%d" % (rel, line),
            "token": token,
            "reason": SURFACE_REASON,
        })
    out.sort(key=lambda s: s["locator"])
    return out


# ─────────────────────── baseline 조립 + write (canonical LF) ─────────────────────

def _assemble(repo_root, gate_flags, declaration_surfaces):
    """schema 순서 고정 dict 조립 (digest 는 gate_flags+surfaces 로만 계산, provenance 제외)."""
    digest = gate.compute_content_digest(gate_flags, declaration_surfaces)
    doc = {}
    doc["schema_version"] = SCHEMA_VERSION
    doc["generated_by"] = GENERATED_BY
    doc["generated_at"] = _git_head_committer_date(repo_root)
    doc["generated_from_commit"] = _git_head_sha(repo_root)
    doc["basis"] = BASIS_TEXT
    doc["content_digest"] = digest
    doc["gate_flags"] = gate_flags
    doc["declaration_surfaces"] = declaration_surfaces
    return doc


def _write_baseline(path, doc):
    """canonical LF-only UTF-8 write (Windows CRLF false-tamper 방지). key 순서 = insertion 순서."""
    body = yaml.safe_dump(
        doc,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        width=100000,
    )
    text = _HEADER + body
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


# ─────────────────────── 서브커맨드: generate ────────────────────────────────────

def cmd_generate(args):
    repo_root = args.repo_root or "."
    registry_path = args.registry or os.path.join(repo_root, gate.DEFAULT_REGISTRY_REL)
    out_path = args.out or os.path.join(repo_root, gate.DEFAULT_BASELINE_REL)

    try:
        entries = gate.load_registry_entries(registry_path)
    except (FileNotFoundError, yaml.YAMLError, ValueError) as e:
        print(
            "[codeforge-evidence-registry-infra-error] gen-deferred-followup-baseline: "
            "registry 로드 실패: %s" % e,
            file=sys.stderr,
        )
        return 2

    gate_flags = collect_gate_flags(entries, repo_root)
    declaration_surfaces = collect_declaration_surfaces(repo_root)
    doc = _assemble(repo_root, gate_flags, declaration_surfaces)
    _write_baseline(out_path, doc)

    print(
        "gen-deferred-followup-baseline: generated %s — gate_flags=%d declaration_surfaces=%d "
        "content_digest=%s (from %s)"
        % (out_path, len(gate_flags), len(declaration_surfaces),
           doc["content_digest"][:12], doc["generated_from_commit"][:12])
    )
    return 0


# ─────────────────────── 서브커맨드: prune (monotonic shrink) ─────────────────────

def cmd_prune(args):
    repo_root = args.repo_root or "."
    baseline_path = args.baseline or os.path.join(repo_root, gate.DEFAULT_BASELINE_REL)

    if not os.path.isfile(baseline_path):
        print(
            "[codeforge-evidence-registry-infra-error] gen-deferred-followup-baseline: "
            "prune 대상 baseline 부재: %s" % baseline_path,
            file=sys.stderr,
        )
        return 2
    try:
        baseline = gate.load_baseline(baseline_path)
    except (yaml.YAMLError, ValueError, OSError) as e:
        print(
            "[codeforge-evidence-registry-infra-error] gen-deferred-followup-baseline: "
            "baseline malformed: %s" % e,
            file=sys.stderr,
        )
        return 2

    # 현재 상태 재평가
    registry_path = os.path.join(repo_root, gate.DEFAULT_REGISTRY_REL)
    try:
        entries = gate.load_registry_entries(registry_path)
    except (FileNotFoundError, yaml.YAMLError, ValueError) as e:
        print(
            "[codeforge-evidence-registry-infra-error] gen-deferred-followup-baseline: "
            "registry 로드 실패: %s" % e,
            file=sys.stderr,
        )
        return 2

    cur_flag_names = {g["name"] for g in collect_gate_flags(entries, repo_root)}
    cur_findings = carrier.scan_repo(repo_root)
    # (rel, token) 집합 — line-drift tolerant membership (grandfather 매치 규칙과 동형)
    cur_surface_keys = {(rel, token) for rel, _line, token, _ctx in cur_findings}

    # gate_flags: 여전히 FLAG 인 것만 유지 (해소분 drop)
    kept_flags = [
        g for g in (baseline.get("gate_flags") or [])
        if isinstance(g, dict) and g.get("name") in cur_flag_names
    ]
    # declaration_surfaces: 토큰이 여전히 존재+미등재인 것만 유지
    kept_surfaces = []
    for s in baseline.get("declaration_surfaces") or []:
        if not isinstance(s, dict):
            continue
        loc = str(s.get("locator", ""))
        s_rel = loc.rsplit(":", 1)[0] if ":" in loc else loc
        s_tok = str(s.get("token", ""))
        if any(s_rel == rel and s_tok == tok for rel, tok in cur_surface_keys):
            kept_surfaces.append({
                "locator": s.get("locator"),
                "token": s.get("token"),
                "reason": s.get("reason", SURFACE_REASON),
            })

    # 정렬 (결정성)
    kept_flags.sort(key=lambda g: str(g.get("name", "")))
    kept_surfaces.sort(key=lambda s: str(s.get("locator", "")))

    dropped_flags = len(baseline.get("gate_flags") or []) - len(kept_flags)
    dropped_surfaces = len(baseline.get("declaration_surfaces") or []) - len(kept_surfaces)

    doc = _assemble(repo_root, kept_flags, kept_surfaces)
    _write_baseline(baseline_path, doc)

    print(
        "gen-deferred-followup-baseline: pruned %s — gate_flags=%d (-%d) "
        "declaration_surfaces=%d (-%d) content_digest=%s"
        % (baseline_path, len(kept_flags), dropped_flags,
           len(kept_surfaces), dropped_surfaces, doc["content_digest"][:12])
    )
    return 0


# ─────────────────────── main ────────────────────────────────────────────────────

def main(argv):
    parser = argparse.ArgumentParser(
        description="deferred-followup baseline single writer (CFP-2591 / ADR-060 §결정 6)"
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    gen_p = subparsers.add_parser("generate", help="registry FLAG + declaration surface 동결 생성")
    gen_p.add_argument("--repo-root", default=".", help="repo root (default: 현재 디렉터리)")
    gen_p.add_argument("--registry", default=None, help="registry yaml 경로 override")
    gen_p.add_argument("--out", default=None, help="baseline 출력 경로 override")

    prune_p = subparsers.add_parser("prune", help="해소분 drop (monotonic shrink only)")
    prune_p.add_argument("--repo-root", default=".", help="repo root (default: 현재 디렉터리)")
    prune_p.add_argument("--baseline", default=None, help="baseline yaml 경로 override")

    args = parser.parse_args(argv[1:])

    if args.command == "generate":
        return cmd_generate(args)
    if args.command == "prune":
        return cmd_prune(args)

    parser.print_help(sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
