#!/usr/bin/env bash
# scripts/post-merge-story-writer.sh — Cross-repo Story §9 row append
# Required env: GH_TOKEN (CODEFORGE_CROSS_REPO_PAT, contents:write on internal-docs)
# Args: --story-key CFP-NN --lane phase:설계-리뷰 --pr-number N --pr-repo owner/repo --decider user_admin

set -euo pipefail

STORY_KEY=""
LANE=""
PR_NUM=""
PR_REPO=""
DECIDER=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --story-key) STORY_KEY="$2"; shift 2 ;;
        --lane) LANE="$2"; shift 2 ;;
        --pr-number) PR_NUM="$2"; shift 2 ;;
        --pr-repo) PR_REPO="$2"; shift 2 ;;
        --decider) DECIDER="$2"; shift 2 ;;
        *) echo "Unknown arg: $1" >&2; exit 1 ;;
    esac
done

if [[ -z "$STORY_KEY" || -z "$LANE" || -z "$PR_NUM" || -z "$PR_REPO" || -z "$DECIDER" ]]; then
    echo "Usage: $0 --story-key CFP-NN --lane phase:X --pr-number N --pr-repo owner/repo --decider DECIDER" >&2
    exit 1
fi

# Map lane label → §9 row lane name
case "$LANE" in
    phase:설계-리뷰) ROW_LANE="설계-리뷰" ;;
    phase:구현-리뷰) ROW_LANE="구현-리뷰" ;;
    phase:보안-테스트) ROW_LANE="보안-테스트" ;;
    *) echo "::notice::Lane not eligible for §9 write: $LANE"; exit 0 ;;
esac

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
NEW_ROW="| 1 | ${ROW_LANE} | TBD | TBD | ${DECIDER} | PASS (${PR_REPO}#${PR_NUM} merged) | ${TIMESTAMP} |"

INTERNAL_DOCS_REPO="mclayer/codeforge-internal-docs"
PLUGIN_FOLDER="${PLUGIN_FOLDER:-wrapper}"
STORY_PATH="${PLUGIN_FOLDER}/stories/${STORY_KEY}.md"
BRANCH="${STORY_KEY,,}-post-merge-followup-pr${PR_NUM}"

# Idempotency check: search §9 for existing row referencing this PR
CURRENT_CONTENT=$(gh api "repos/${INTERNAL_DOCS_REPO}/contents/${STORY_PATH}" --jq '.content' | base64 -d)
if echo "$CURRENT_CONTENT" | grep -q "${PR_REPO}#${PR_NUM} merged"; then
    echo "::notice::§9 row for ${PR_REPO}#${PR_NUM} already exists (idempotent skip)"
    exit 0
fi

# Append §9 row
NEW_CONTENT=$(echo "$CURRENT_CONTENT" | awk -v new_row="$NEW_ROW" '
    /^## §9 / { in_section = 1; print; next }
    in_section && /^\| Iter \|/ { print; getline; print; print new_row; in_section = 0; next }
    /^## §10/ && in_section { print new_row; in_section = 0 }
    { print }
')

# Get current file SHA
SHA=$(gh api "repos/${INTERNAL_DOCS_REPO}/contents/${STORY_PATH}" --jq '.sha')
NEW_CONTENT_B64=$(echo "$NEW_CONTENT" | base64 -w0)

# Create branch (PR-specific to avoid concurrent conflict)
MAIN_SHA=$(gh api "repos/${INTERNAL_DOCS_REPO}/git/refs/heads/main" --jq '.object.sha')
gh api -X POST "repos/${INTERNAL_DOCS_REPO}/git/refs" \
    -f ref="refs/heads/${BRANCH}" -f sha="$MAIN_SHA" 2>/dev/null || true

# PUT file on branch
gh api -X PUT "repos/${INTERNAL_DOCS_REPO}/contents/${STORY_PATH}" \
    -f message="docs(${STORY_KEY,,}): post-merge §9 PASS auto-write (${PR_REPO}#${PR_NUM})" \
    -f content="$NEW_CONTENT_B64" \
    -f sha="$SHA" \
    -f branch="$BRANCH"

# Open PR
gh pr create -R "$INTERNAL_DOCS_REPO" \
    --base main --head "$BRANCH" \
    --title "${STORY_KEY} post-merge §9 auto-write (${PR_REPO}#${PR_NUM})" \
    --body "Auto-generated by post-merge-followup workflow. Decider: ${DECIDER}. Source PR: ${PR_REPO}#${PR_NUM}."

echo "::notice::§9 row appended to ${STORY_PATH}, PR opened on ${BRANCH}"
